name: "Rich Navigation Indexing"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  richnav:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: node -v
    - run: pwd
    - uses: microsoft/RichCodeNavIndexer@diagnose
      with:
        languages: 'csharp,typescript,java,cpp'
        environment: 'development'
      continue-on-error: true
