name: "Rich Navigation Indexing"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  richnav:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - uses: microsoft/RichCodeNavIndexer@v0
      with:
        languages: 'csharp,typescript,java,cpp'
        environment: 'development'
      continue-on-error: true
